INSERT INTO public.subjects (name, code, program, semester_or_year) VALUES
('Business English', 'MGT 201', 'BBS', '1st Year'),
('Business Statistics', 'MGT 202', 'BBS', '1st Year'),
('Microeconomics for Business', 'MGT 207', 'BBS', '1st Year'),
('Financial Accounting and Analysis', 'MGT 211', 'BBS', '1st Year'),
('Principles of Management', 'MGT 213', 'BBS', '1st Year'),
('Business Communication', 'MGT 205', 'BBS', '2nd Year'),
('Macroeconomics for Business', 'MGT 209', 'BBS', '2nd Year'),
('Cost and Management Accounting', 'MGT 212', 'BBS', '2nd Year'),
('Fundamentals of Marketing', 'MGT 214', 'BBS', '3rd Year'),
('Business Law', 'MGT 204', 'BBS', '3rd Year'),
('Fundamentals of Financial Management', 'MGT 215', 'BBS', '2nd Year'),
('Taxation in Nepal', 'MGT 224', 'BBS', '3rd Year'),
('Organizational Bahaviour & Human Resource Management', 'MGT 223', 'BBS', '2nd Year'),
('Fundamentals of Corporate Finance', 'FIN 250', 'BBS', '4th Year'),
('Fundamentals of Investment', 'FIN 253', 'BBS', '4th Year'),
('Business Research Methods', 'MGT 221', 'BBS', '4th Year'),
('Final Project', 'MGT 401', 'BBS', '4th Year'),
('Foundation of Financial Systems', 'MGT 226', 'BBS', '3rd Year'),
('Entrepreneurship', 'MGT 225', 'BBS', '4th Year'),
('Management of Financial Institutions', 'FIN 255', 'BBS', '4th Year'),
('General English', 'Eng.Ed.411', 'B.Ed', '1st Year'),
('Compulsory Nepali', 'Nep. 401', 'B.Ed', '1st Year'),
('Philosophical and Sociological Foundations of Education', 'Ed.412', 'B.Ed', '1st Year'),
('Foundation of Language and Linguistics', 'Eng.Ed.416', 'B.Ed', '1st Year'),
('Reading Writing and Critical Thinking', 'Eng. Ed. 417', 'B.Ed', '1st Year'),
('Nepali Katha Ra Upanyas', 'Nep.Ed.416', 'B.Ed', '1st Year'),
('Nepali Natak Ekanki Ra Nibandha', 'Nep.Ed.417', 'B.Ed', '1st Year'),
('Educational Psychology', 'Ed.421', 'B.Ed', '2nd Year'),
('Expanding Horizons in English', 'Eng.Ed.422', 'B.Ed', '2nd Year'),
('English for Communication', 'Eng.Ed.423', 'B.Ed', '2nd Year'),
('Basics of Academic Writing', 'Eng.Ed.424', 'B.Ed', '2nd Year'),
('Bhasa Bigyan ra Nepali Bhasa', 'Nep.Ed.422', 'B.Ed', '2nd Year'),
('Nepali Kabita Kabya', 'Nep.Ed.423', 'B.Ed', '2nd Year'),
('Nepali Bhasa Pathya., Pathyapustak tatha Sikshen Paddati', 'Nep.Ed.424', 'B.Ed', '2nd Year'),
('Curriculum and Evaluation', 'Ed.431', 'B.Ed', '3rd Year'),
('English Language Teaching Methods and Practices', 'Eng.Ed.432', 'B.Ed', '3rd Year'),
('Critical Reading in English', 'Eng.Ed.433', 'B.Ed', '3rd Year'),
('English for Mass Communication', 'Eng.Ed.434', 'B.Ed', '3rd Year'),
('Nepali Bhasa Sikshen', 'Nep.Ed.432', 'B.Ed', '3rd Year'),
('Prayogic Bhasa Bigyan', 'Nep.Ed.433', 'B.Ed', '3rd Year'),
('Shaityashasatra ra Nepali Samalochana', 'Nep.Ed.434', 'B.Ed', '3rd Year'),
('Teaching Practice', 'Ed.440', 'B.Ed', '4th Year'),
('Classroom Instruction', 'Ed.442', 'B.Ed', '4th Year'),
('Research Methodology in English', 'Eng.Ed.445', 'B.Ed', '4th Year'),
('Literature for Language Development', 'Eng.Ed.446', 'B.Ed', '4th Year'),
('Anushandhan Bidhi', 'Nep.Ed.445', 'B.Ed', '4th Year'),
('Bayabharik Lekhan Ra Sampadan', 'Nep.Ed.446', 'B.Ed', '4th Year'),
('Population Dynamics', 'Pop.Ed.429', 'B.Ed', '2nd Year'),
('Method of Teaching Population Education', 'Pop.Ed.432', 'B.Ed', '3rd Year'),
('Business Envi. & Startegic Mgmt', 'MGT 217', 'BBS', '3rd Year'),
('Fundamentals of Selling', 'MKT 250', 'BBS', '4th Year'),
('Fundamentals of Advertising', 'MKT 253', 'BBS', '4th Year'),
('Fundamentals of Services Marketing', 'MKT 254', 'BBS', '4th Year'),
('Managerial Economics', 'ECO 512', 'MBS', '1st Sem'),
('Statistical Methods', 'MSC 514', 'MBS', '1st Sem'),
('Organizational Behavior', 'MGT 515', 'MBS', '1st Sem'),
('Managerial Communication', 'MGT 519', 'MBS', '1st Sem'),
('Financial Management', 'FIN 510', 'MBS', '2nd Sem'),
('Human Resource Management', 'MGT 513', 'MBS', '2nd Sem'),
('Accounting for Financial and Managerial Decision and Control', 'ACC 519', 'MBS', '3rd Sem'),
('Research Methodology', 'MSC 521', 'MBS', '3rd Sem'),
('International Business', 'MGT 522', 'MBS', '3rd Sem'),
('Entrepreneurship', 'MGT 524', 'MBS', '3rd Sem'),
('Corporate Finance', 'FIN 688', 'MBS', '3rd Sem'),
('Advertising and Promotion Management', 'MKT 691', 'MBS', '3rd Sem'),
('Strategic Management', 'MGT 523', 'MBS', '4th Sem'),
('Financial Markets and Institutions', 'FIN 685', 'MBS', '4th Sem'),
('Marketing Management', 'MKT 511', 'MBS', '1st Sem'),
('Foundation of Population Education', 'Pop.Ed.418', 'B.Ed', '1st Year'),
('Population Situation of Nepal', 'Pop.Ed.428', 'B.Ed', '2nd Year'),
('Methods of Teaching Population Education', 'Pop.Ed.439', 'B.Ed', '3rd Year'),
('Project Work and Seminar on Population Edu.', 'Pop.Ed.449', 'B.Ed', '4th Year'),
('Economics for Business', 'ECO 206', 'BIM', '4th Sem'),
('Cost and Management Accounting', 'ACC 202', 'BIM', '4th Sem'),
('Database Management System', 'IT 220', 'BIM', '4th Sem'),
('Web Technology II', 'IT 239', 'BIM', '4th Sem'),
('Business Data Communication and Networking', 'IT 240', 'BIM', '4th Sem'),
('Operating System', 'IT 241', 'BIM', '4th Sem'),
('Business Communication', 'ENG 203', 'BIM', '1st Sem'),
('Organizational Behavior and Human Resource Management', 'MGT 241', 'BIM', '1st Sem'),
('Discrete Structure', 'IT 235', 'BIM', '1st Sem'),
('Digital Logic', 'IT 233', 'BIM', '1st Sem'),
('Object Oriented Programming with Java', 'IT 234', 'BIM', '1st Sem'),
('English II', 'ENG 151', 'BHM', '2nd Sem'),
('Organizational Behavior and Human Resource Management', 'MGT 151', 'BHM', '2nd Sem'),
('Financial Accounting', 'ACC 151', 'BHM', '1st Sem'),
('Food Production Patisserie II', 'BHM 151', 'BHM', '2nd Sem'),
('Food and Beverage Service II', 'BHM 152', 'BHM', '2nd Sem'),
('Housekeeping Operations II', 'BHM 153', 'BHM', '2nd Sem'),
('English I', 'ENG 206', 'BIM', '1st Sem'),
('Foundation of Business Management', 'MGT 231', 'BIM', '1st Sem'),
('Basic Mathematics', 'MTH 204', 'BIM', '1st Sem'),
('Foundation of Information Technology', 'IT 231', 'BIM', '1st Sem'),
('C Programming', 'IT 232', 'BIM', '1st Sem'),
('Financial Accounting', 'ACC 201', 'BIM', '3rd Sem'),
('Business Statistics', 'STT 201', 'BIM', '3rd Sem'),
('Microprocessor and Computer Architecture', 'IT 236', 'BIM', '3rd Sem'),
('Web Technology I', 'IT 237', 'BIM', '3rd Sem'),
('Data Structure and Algorithms', 'IT 238', 'BIM', '3rd Sem'),
('English-I', 'ENG 101', 'BHM', '1st Sem'),
('Principles of Management', 'MGT 101', 'BHM', '1st Sem'),
('Hotel French', 'BHM 101', 'BHM', '1st Sem'),
('Food Production and Patisserie I', 'BHM 102', 'BHM', '1st Sem'),
('Food and Beverage Service I', 'BHM 103', 'BHM', '1st Sem'),
('Housekeeping Operations I', 'BHM 104', 'BHM', '1st Sem'),
('Sales and Marketing', 'MKT 201', 'BHM', '3rd Sem'),
('Food Science and Nutrition', 'BHM 201', 'BHM', '3rd Sem'),
('Food Production Operations', 'BHM 202', 'BHM', '3rd Sem'),
('Bar and Beverage Service', 'BHM 203', 'BHM', '3rd Sem'),
('Front Office Operations I', 'BHM 204', 'BHM', '3rd Sem'),
('Organizational Behavior', 'MGT 203', 'BIM', '7th Sem'),
('Business Strategy', 'MGT 208', 'BIM', '7th Sem'),
('Management Information System', 'IT 226', 'BIM', '7th Sem'),
('Object Oriented Analysis and Design', 'IT 227', 'BIM', '7th Sem'),
('Artificial Intelligence', 'IT 228', 'BIM', '7th Sem'),
('Software Design and Development', 'IT 242', 'BIM', '5th Sem'),
('Programming with Python', 'IT 243', 'BIM', '5th Sem'),
('Information Security', 'IT 244', 'BIM', '5th Sem'),
('Business Research Methods', 'RCH 201', 'BIM', '6th Sem'),
('Fundamentals of Corporate Finance', 'FIN 229', 'BIM', '6th Sem'),
('Business Environment', 'MGT 236', 'BIM', '6th Sem'),
('IT Ethics and Cybersecurity', 'IT 246', 'BIM', '6th Sem'),
('Project', 'IT 352', 'BIM', '6th Sem'),
('IT Entrepreneurship and Supply Chain Management', 'IT 229', 'BIM', '8th Sem'),
('Economics of Information and Communication', 'IT 230', 'BIM', '8th Sem'),
('Introduction to Computing and Information Technology', 'ITM 101', 'BITM', '1st Sem'),
('Structured Programming in C', 'ITM 102', 'BITM', '1st Sem'),
('English I', 'ENG 103', 'BITM', '1st Sem'),
('Foundation of Business Management', 'MGT 103', 'BITM', '1st Sem'),
('Basic Mathematics', 'MTH 103', 'BITM', '1st Sem'),
('English Composition', 'ENG 201', 'BIM', '1st Sem'),
('Basic Mathematics', 'MTH 201', 'BIM', '1st Sem'),
('Computer Information System', 'IT 211', 'BIM', '1st Sem'),
('Digital Logic Design', 'IT 212', 'BIM', '1st Sem'),
('Sociology for Business', 'SOC 201', 'BIM', '2nd Sem'),
('Discrete Mathemetics and Its Application', 'MTH 202', 'BIM', '2nd Sem'),
('Structured Programming', 'IT 213', 'BIM', '2nd Sem'),
('Data Communication and Computer Network', 'IT 214', 'BIM', '2nd Sem'),
('Web Programming I', 'IT 215', 'BIM', '3rd Sem'),
('JAVA Programming I', 'IT 216', 'BIM', '3rd Sem'),
('Computer Organization', 'IT 217', 'BIM', '3rd Sem'),
('Micro Economics', 'ECO 201', 'BIM', '4th Sem'),
('Data Stfucture and Algorithm With JAVA', 'IT 218', 'BIM', '4th Sem'),
('Web Programming II', 'IT 219', 'BIM', '4th Sem'),
('Macro Economics', 'ECO 202', 'BIM', '5th Sem'),
('Computer Graphis', 'IT 221', 'BIM', '5th Sem'),
('Java Programming II', 'IT 222', 'BIM', '5th Sem'),
('Advance Internetworking', 'IT 223', 'BIM', '5th Sem'),
('Business Finance', 'FIN 201', 'BIM', '6th Sem'),
('Business Environment in Nepal', 'MGT 206', 'BIM', '6th Sem'),
('Software Engineering', 'IT 224', 'BIM', '6th Sem'),
('Computer Security and Cyber Law', 'IT 225', 'BIM', '6th Sem'),
('Summer Project', 'IT 351', 'BIM', '6th Sem'),
('Software Project Management', 'IT 306', 'BIM', '8th Sem'),
('Operating Systems', 'IT 307', 'BIM', '8th Sem'),
('Data Mining and Data Warehousing', 'IT 308', 'BIM', '8th Sem'),
('Internship', 'IT 350', 'BIM', '8th Sem'),
('International Markets', 'MKT 686', 'MBS', '4th Sem'),
('IT Entrepreneurship and Management', 'IT 248', 'BIM', '8th Sem'),
('Cloud Computing', 'IT 277', 'BIM', '8th Sem'),
('Business Intelligence', 'IT 249', 'BIM', '8th Sem'),
('Digital Economy', 'IT 250', 'BIM', '8th Sem'),
('Entrepreneurship for Hospitality', 'BHM 329', 'BHM', '8th Sem'),
('Strategic Management', 'BHM 312', 'BHM', '8th Sem'),
('Nepalese Society and Politics', 'SOC 202', 'BHM', '8th Sem'),
('Quality Management', 'BHM 451', 'BHM', '8th Sem'),
('Organization Behavior', 'MGT 313', 'BHM', '8th Sem'),
('E-Commerce and Internet Marketing', 'IT 247', 'BIM', '7th Sem'),
('Data Warehousing and Data Mining', 'IT 274', 'BIM', '7th Sem'),
('Sociology for Business Management', 'SOC 203', 'BIM', '7th Sem'),
('Strategic Management', 'MGT 240', 'BIM', '7th Sem'),
('E-Commerce for Hospitality', 'BHM 301', 'BHM', '5th Sem'),
('Entrepreneurship', 'MGT 301', 'BHM', '5th Sem'),
('Event Management for Tourism and Hospitality', 'BHM 302', 'BHM', '5th Sem'),
('Statistics', 'STT 301', 'BHM', '5th Sem'),
('Economics', 'ECO 301', 'BHM', '5th Sem')
ON CONFLICT (code) DO NOTHING;